// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	KVDATA: KVNamespace;
	JWT_AUTH: "9f2b7c1a4d8e5f6a3b1c9d0e7f4a6b8c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7";
	R2_BUCKET: R2Bucket;
	DB: D1Database;
	AI: Ai;
}
